<?php
/** 
 * Installation of the tripal protein structure module
 */

/**
 * Implements hook_install().
 * 
 * @ingroup tripal_protein_structure
 */
function tripal_protein_structure() {

}

/ **
 * Implementation of hook_schema().
 * 
 * @ingroup tripal_protein_structure
 */
function tripal_protein_structure_schema() {
    $['tripal_fold'] = array(
        'fields' => array(
	    'nid' => array(
		'type' => 'int',
		'unsigned' => TRUE,
		'not null' => TRUE,
		'default' => 0,
	    )
	    'structure_id' => array(
		'type' => 'int',
		'not null' => TRUE,
		'default' => 0,
	    ),
	    'structure_loc' => array(
		'type' => 'varchar',
		'length' => 255,
		'not null' => TRUE,
	    ),
	)
    )
}

