<?php
/**
* @file
* Basic functionality for tripal fold module.
*/

/** 
* Implements hook_help()
*
* Display help and module information
*
* @ingroup tripal_fold
*/

function tripal_fold_help($path, $arg) {
    if($path == 'admin/help#tripal_fold' || $path == 'admin/tripal/extension/tripal_fold/help') {
	return t('Protein Structure Mapping Module');
    }
}

/**
* Implements hook_permission().
* 
* Set the permissions types used by the tripal protein structure module.
*
* @ingroup tripal_fold
*/

function tripal_fold_permission() {
    return array(
	'use fold module' => array(
	    'title' => t('Administer Protein Structure'),
	    'description' => t('Allow users to browse three-dimensional structure of proteins'),
	    )
    );
}


