<?php
/** 
 * Installation of the tripal protein structure module
 */

/**
 * Implementation of hook_schema().
 * 
 * @ingroup tripal_protein_structure
 */
function tripal_fold_schema() {
    $schema['tripal_fold'] = array(
        'fields' => array(
	    'feature_id' => array(
		'type' => 'int',
		'not null' => TRUE,
   	    ),
	    'structure_id' => array(
		'type' => 'int',
		'not null' => TRUE,
		'default' => 0,
	    ),
	    'structure_loc' => array(
		'type' => 'varchar',
		'length' => 255,
		'not null' => TRUE,
	    ),
	),
	'primary key' => array('structure_id'),
	'foreign keys' => array(
	    'feature_id' => array(
		'table' => 'feature',
		'columns' => array(
		    'feature_id' => 'feature_id',
		)
	    )
	)
    );
}

/**
 * Implementation of hook_uninstall()
 * 
 * @ingroup tripal_fold
 */
function tripal_fold_uninstall() {
}




 
