<?php
/**
* @file
* Basic functionality for tripal protein structure module.
*/

/** 
* Implements hook_help()
*
* Display help and module information
*
* @ingroup tripal_protein_structure
*/

function tripal_protein_structure_help($path, $arg) {
    if($path == 'admin/help#tripal_protein_structure' || $path == 'admin/tripal/extension/tripal_protein_structure/help') {
	return t('Protein Structure Mapping Module');
    }
}

/**
* Implements hook_permission().
* 
* Set the permissions types used by the tripal protein structure module.
*
* @ingroup tripal_protein_structure
*/

function tripal_protein_structure_permission() {
    return array(
	'use protein_structure module' => array(
	    'title' => t('Administer Protein Structure'),
	    'description' => t('Allow users to browse three-dimensional structure of proteins'),
	    )
    );
}


