<?php
/** 
 * Installation of the tripal protein structure module
 */

/**
 * Implements hook_install().
 * 
 * @ingroup tripal_protein_structure
 */
function tripal_protein_structure() {

}

/ **
 * Implementation of hook_schema().
 * 
 * @ingroup tripal_protein_structure
 */
function tripal_protein_structure_schema() {
    $['schema'] = array(
        'fields' => array(
	    'structure_id' => array(
		'type' => 'int',
		'not null' => true,
	    ),
	)
    )
}

